CREATE TABLE [g100].[LINEITEM] (
    [L_ORDERKEY]      INT             NOT NULL,
    [L_PARTKEY]       INT             NOT NULL,
    [L_SUPPKEY]       INT             NOT NULL,
    [L_LINENUMBER]    INT             NOT NULL,
    [L_QUANTITY]      DECIMAL (15, 2) NOT NULL,
    [L_EXTENDEDPRICE] DECIMAL (15, 2) NOT NULL,
    [L_DISCOUNT]      DECIMAL (15, 2) NOT NULL,
    [L_TAX]           DECIMAL (15, 2) NOT NULL,
    [L_RETURNFLAG]    CHAR (1)        NOT NULL,
    [L_LINESTATUS]    CHAR (1)        NOT NULL,
    [L_SHIPDATE]      DATE            NOT NULL,
    [L_COMMITDATE]    DATE            NOT NULL,
    [L_RECEIPTDATE]   DATE            NOT NULL,
    [L_SHIPINSTRUCT]  CHAR (25)       NOT NULL,
    [L_SHIPMODE]      CHAR (10)       NOT NULL,
    [L_COMMENT]       VARCHAR (44)    NOT NULL,
    CONSTRAINT [LINEITEM_FK1] FOREIGN KEY ([L_ORDERKEY]) REFERENCES [dbo].[ORDERS] ([O_ORDERKEY]),
    CONSTRAINT [LINEITEM_FK2] FOREIGN KEY ([L_PARTKEY], [L_SUPPKEY]) REFERENCES [dbo].[PARTSUPP] ([PS_PARTKEY], [PS_SUPPKEY])
);


GO
CREATE CLUSTERED INDEX [IX_LINEITEM_SHIPDATE_g100]
    ON [g100].[LINEITEM]([L_SHIPDATE] ASC);

