CREATE TABLE [g100].[REGION] (
    [R_REGIONKEY] INT           NOT NULL,
    [R_NAME]      CHAR (25)     NOT NULL,
    [R_COMMENT]   VARCHAR (152) NULL,
    PRIMARY KEY CLUSTERED ([R_REGIONKEY] ASC)
);

