CREATE TABLE [g1].[CUSTOMER] (
    [C_CUSTKEY]    INT             NOT NULL,
    [C_NAME]       VARCHAR (25)    NOT NULL,
    [C_ADDRESS]    VARCHAR (40)    NOT NULL,
    [C_NATIONKEY]  INT             NOT NULL,
    [C_PHONE]      CHAR (15)       NOT NULL,
    [C_ACCTBAL]    DECIMAL (15, 2) NOT NULL,
    [C_MKTSEGMENT] CHAR (10)       NOT NULL,
    [C_COMMENT]    VARCHAR (117)   NOT NULL,
    PRIMARY KEY CLUSTERED ([C_CUSTKEY] ASC),
);

