CREATE TABLE [dbo].[PARTSUPP] (
    [PS_PARTKEY]    INT             NOT NULL,
    [PS_SUPPKEY]    INT             NOT NULL,
    [PS_AVAILQTY]   INT             NOT NULL,
    [PS_SUPPLYCOST] DECIMAL (15, 2) NOT NULL,
    [PS_COMMENT]    VARCHAR (199)   NOT NULL,
    PRIMARY KEY CLUSTERED ([PS_PARTKEY] ASC, [PS_SUPPKEY] ASC),
);

