name: CD-SQLDB

on:
  workflow_run:
    workflows: [CI-SQLDB-MSBuild]
    types:
      - completed

  workflow_dispatch:

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_WORKSPACE: AzureSqlDB\01AdvDb\
  SOLUTION_FILE_PATH: 01AdvDb.sqlproj
  ARTIFACT_NAME: AdvWorks2016

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  Deploy-SQLDB:
    runs-on: windows-latest

    steps:
    - uses: actions/download-artifact@v3
      with:
        repo: HarveyHuBJ/MsDataOpsStarter
        token: ${{ secrets.GITHUB_TOKEN }}
        name: ${{ env.ARTIFACT_NAME }}
        path: path/to/artifact
        
    - name: Display structure of downloaded files
      run: dir
      working-directory: path/to/artifact




      

        
