name: CD-03-Blob

on:
  workflow_run:
    workflows: [CI-03-Blob]
    types:
      - completed

  workflow_dispatch:
  push:
    branches:
      - "main"
env:
  # Path to the solution file relative to the root of the project.
  ARTIFACT_NAME: Data
  STORAGE_ACCOUNT: storagehh101dev 
  SRC_DATA: srcdata

permissions:
  contents: read

jobs:
  Deploy-SQLDB:
    runs-on: ubuntu-latest

    steps:
    - name: Download dacpac from CI
      uses: aochmann/actions-download-artifact@1.0.4
    # - uses: actions/download-artifact@v3
      with:
        repo: HarveyHuBJ/MsDataOpsStarter
        github_token: ${{ secrets.GITHUB_TOKEN }}
        name: ${{ env.ARTIFACT_NAME }}
        path: ${{ env.SRC_DATA }}
        
    - name: Display structure of downloaded files
      run: tree .
      working-directory: ${{ env.SRC_DATA }}
    # - uses: azure/login@v1                            # dataops_spn
    #   with:
    #     creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Azure CLI script - az copy data
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az storage container create --name srcdata --account-name  ${{ env.STORAGE_ACCOUNT }} --account-key ${{secrets.STORAGE_KEY_101}}
          az storage blob upload-batch -s ${{ env.SRC_DATA }} -d srcdata --account-name  ${{ env.STORAGE_ACCOUNT }} --account-key ${{secrets.STORAGE_KEY_101}}


      

        
