name: CD-02-ADF

on:
  workflow_run:
    workflows: [CI-02-ADF]
    types:
      - completed

  workflow_dispatch:

env:
  RESOURCE_GROUP_NAME: rg-dataops-starter
  DATA_FACTORY_NAME: adf-hh101-dev
  ARM_FILE_NAME: ArmTemplateOutput/ARMTemplateForFactory.json

jobs:
  publish-adf:
    runs-on: ubuntu-latest

    steps:
      - name: Download dacpac from CI
        uses: aochmann/actions-download-artifact@1.0.4
    # - uses: actions/download-artifact@v3
        with:
          repo: HarveyHuBJ/MsDataOpsStarter
          github_token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ env.ARTIFACT_NAME }}
          path: .

      - uses: azure/login@v1                            # Azure login required to add a temporary firewall rule
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy Data Factory
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
          dataFactoryName: ${{ env.DATA_FACTORY_NAME }}
          armTemplateFile: ${{ env.ARM_FILE_NAME }}
          

