name: CD-04-Databricks

on:
  workflow_run:
    workflows: [CI-04-Databricks]
    types:
      - completed

  workflow_dispatch:
  workflow_call:
  # push:
  #   branches:
  #     - "main"
env:
  FAMILY_NAME: hh101 
  ENV_NAME: sit 
  KEY_VAULT: kv-hh101-dev
  ARTIFACT_NAME: az_databricks_artifact
  RESOURCE_GROUP_NAME: rg-dataops-starter
  DATABRICKS_HOST: https://adb-6136766911067460.0.azuredatabricks.net/
  LOCAL_NOTEBOOKS_PATH: ./dist                                            # used in step databricks-import-directory
  REMOTE_NOTEBOOK_PATH: /Users/adminuser@cpuhackthon.onmicrosoft.com/src  # used in step databricks-import-directory
# Get-AzDataFactoryV2Trigger -ResourceGroupName rg-dataops-starter -DataFactoryName adf-hh101-dev
jobs:
  publish-adf:
    runs-on: ubuntu-latest

    steps:
#### Download Artifact
      - name: Download artifact from CI
        uses: aochmann/actions-download-artifact@1.0.4
        with:
          repo: HarveyHuBJ/MsDataOpsStarter
          github_token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ env.ARTIFACT_NAME }}
          path: dist

##### install databricks CLI
      - name: install-databricks-cli
        uses: microsoft/install-databricks-cli@main

#### az login to access key vault 
      - name: az login with github_dataops_spn
        uses: azure/login@v1                            # github_dataops_spn
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
#### retrieve databricks token
      - uses: Azure/get-keyvault-secrets@v1
        id: getSecretAction # ID for secrets that you will reference
        name: retrieve databricks token
        with:
          keyvault: ${{env.KEY_VAULT}} # name of key vault in Azure portal
          secrets: 'secret-databricks-token'  # comma separated list of secret keys to fetch from key vault 


# #### databricks-import-directory
      - name: databricks-import-directory
        run: | 
          echo "Uploading notebooks from $LOCAL_NOTEBOOKS_PATH to $REMOTE_NOTEBOOK_PATH in the workspace $DATABRICKS_HOST"
          databricks workspace import_dir --overwrite "${LOCAL_NOTEBOOKS_PATH}" "${REMOTE_NOTEBOOK_PATH}" --debug
        shell: bash
        env:
          DATABRICKS_TOKEN:   ${{steps.getSecretAction.outputs.secret-databricks-token}}  

 

