name: CD-01-SQLDB

on:
  workflow_run:
    workflows: [CI-01-SQLDB-MSBuild]
    types:
      - completed

  workflow_dispatch:
  # push:
  #   branches:
  #     - "main"
env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_WORKSPACE: AzureSqlDB\01AdvDb\
  SOLUTION_FILE_PATH: 01AdvDb.sqlproj
  ARTIFACT_NAME: AdvWorks2016
  KEY_VAULT: kv-hh101-dev
  DB_SERVER: dbsrv-hh101-dev.database.windows.net
  DB_NAME: db-hh101-dev
  DB_USER_LOGIN: db_admin

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  Deploy-SQLDB:
    runs-on: ubuntu-latest

    steps:
    - name: Download dacpac from CI
      uses: aochmann/actions-download-artifact@1.0.4
    # - uses: actions/download-artifact@v3
      with:
        repo: HarveyHuBJ/MsDataOpsStarter
        github_token: ${{ secrets.GITHUB_TOKEN }}
        name: ${{ env.ARTIFACT_NAME }}
        path: .
        
    - name: Display structure of downloaded files
      run: dir
      working-directory: .
    - uses: azure/login@v1                            # Azure login required to add a temporary firewall rule
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: Azure/get-keyvault-secrets@v1
      id: getSecretAction # ID for secrets that you will reference
      name: retrieve dbadmin password
      with:
        keyvault: ${{env.KEY_VAULT}} # name of key vault in Azure portal
        secrets: 'secret-dbadmin-pwd'  # comma separated list of secret keys to fetch from key vault 
     
    - name: Azure SQL Deploy
      uses: Azure/sql-action@v1.3
      with:
        # Name of the Azure SQL Server name, like Fabrikam.database.windows.net.
        # server-name: ${{env.DB_SERVER}} # optional
        # The connection string, including authentication information, for the Azure SQL Server database.
        connection-string: Server=tcp:${{env.DB_SERVER}},1433;Initial Catalog=${{env.DB_NAME}};Persist Security Info=False;User ID=${{env.DB_USER_LOGIN}};Password=${{steps.getSecretAction.outputs.secret-dbadmin-pwd}};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;
        # Path to DACPAC file to deploy
        dacpac-package: 01AdvDb.dacpac # optional
        # In case DACPAC option is selected, additional SqlPackage arguments that will be applied. When SQL query option is selected, additional sqlcmd arguments will be applied.
        arguments: "/dsp:deploy_script.sql /p:IgnoreColumnOrder=true" # optional

    - name: Upload deploy_script Artifact
      uses: actions/upload-artifact@v3
      with:
        name: deploy_script
        path: deploy_script*.*


      

        
