name: CD-01-SQLDB

on:
  workflow_run:
    workflows: [CI-01-SQLDB-MSBuild]
    types:
      - completed

  workflow_dispatch:
  push:
    branches:
      - "main"
env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_WORKSPACE: AzureSqlDB\01AdvDb\
  SOLUTION_FILE_PATH: 01AdvDb.sqlproj
  ARTIFACT_NAME: AdvWorks2016

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

  DB_SERVER: dbsrv-hh101-dev.database.windows.net
permissions:
  contents: read

jobs:
  Deploy-SQLDB:
    runs-on: ubuntu-latest

    steps:
    - name: Download dacpac from CI
      uses: aochmann/actions-download-artifact@1.0.4
    # - uses: actions/download-artifact@v3
      with:
        repo: HarveyHuBJ/MsDataOpsStarter
        github_token: ${{ secrets.GITHUB_TOKEN }}
        name: ${{ env.ARTIFACT_NAME }}
        path: .
        
    - name: Display structure of downloaded files
      run: dir
      working-directory: .
    - uses: azure/login@v1                            # Azure login required to add a temporary firewall rule
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Azure SQL Deploy
      uses: Azure/sql-action@v1.3
      with:
        # Name of the Azure SQL Server name, like Fabrikam.database.windows.net.
        # server-name: ${{env.DB_SERVER}} # optional
        # The connection string, including authentication information, for the Azure SQL Server database.
        connection-string: ${{secrets.SQL_CONNECTION_STRING}}
        # Path to DACPAC file to deploy
        dacpac-package: 01AdvDb.dacpac # optional
        # In case DACPAC option is selected, additional SqlPackage arguments that will be applied. When SQL query option is selected, additional sqlcmd arguments will be applied.
        arguments: "/dsp:deploy_script.sql /p:IgnoreColumnOrder=true" # optional

    - name: Upload deploy_script Artifact
      uses: actions/upload-artifact@v3
      with:
        name: deploy_script
        path: deploy_script*.*


      

        
