name: CI-03-Blob

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_WORKSPACE: 00Data
  ARTIFACT_NAME: Data

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

jobs:
  Deploy-SQLDB:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: browser
      run: tree .
    - name: Copy to Artifact Folder
      run: |
        mkdir -p ./artifacts/ci-run/${{github.RUN_NUMBER}}/ 
        cp -r ${{env.SOLUTION_WORKSPACE}}/ ./artifacts/ci-run/${{github.RUN_NUMBER}}/
    - name: Upload Data Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{env.ARTIFACT_NAME}}$
        path: ./artifacts/ci-run/${{github.RUN_NUMBER}}/


      

        
