name: CI-02-ADF

on:
  push:
    branches:
      - "main"
  workflow_dispatch:
  workflow_call:

env:
  ARTIFACT_NAME: adf

jobs:
  build-adf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

#### Export ADF built template
      - name: export adf template
        working-directory: ./ADF
        run: |
          npm install
          npm run build export ./ /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/testResourceGroup/providers/Microsoft.DataFactory/factories/DevDataFactory ../ArmTemplateOutput
      
#### Copy to Artifact Folder, and add readme.txt
      - name: Copy to Artifact Folder
        run: |
          mkdir -p ./artifacts/ci-run/${{github.RUN_NUMBER}}/ 
          cp -r ./ArmTemplateOutput/ ./artifacts/
          echo 'ci-run:${{github.RUN_NUMBER}}'> ./artifacts/readme.txt

#### Upload Artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{env.ARTIFACT_NAME}}
          path: ./artifacts

